version: '3'

services:
  backend:
    build:
      context: ./.
      dockerfile: Dockerfile 
    command: bash entrypoint.prod.sh
    #environment:
    #  - DB_NAME=${DB_NAME}
    #  - DB_USERNAME=${DB_USERNAME}
    #  - DB_PASSWORD=${DB_PASSWORD}
    #  - DB_HOST=database 
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - 8000:8000
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/static/
    depends_on:
      - backend
    
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data