apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  progressDeadlineSeconds: 5000
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image:  bookxchangedevelopment.azurecr.io/backend-dev:latest
        imagePullPolicy: Always
        imagepullsecrets:
        - name: registry-secrets
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        envFrom:
          - secretRef:
              name: django-secrets
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: django-service 
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: django 
  type: LoadBalancer
  ports:
  - port: 80 
    targetPort: 8000 

