name: Build docker container and push to ACR 

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  django-test-job:
    uses: TeamPWNED/BookXchange-backend/.github/workflows/test.yaml@main
    secrets: inherit
  docker-build:
    runs-on: ubuntu-latest
    needs: ['django-test-job']
    env:
      DEBUG: True
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login into Azure Container Registry 
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.DEV_REGISTRY_LOGIN_SERVER }} 
          username: ${{ secrets.DEV_REGISTRY_USERNAME }}
          password: ${{ secrets.DEV_REGISTRY_PASSWORD }}
      - name: Build Image
        run: |
          docker build -f Dockerfile . -t ${{ secrets.DEV_REGISTRY_LOGIN_SERVER }}/backend-dev:${{ github.sha }} \
                                       -t ${{ secrets.DEV_REGISTRY_LOGIN_SERVER }}/backend-dev:latest 
      - name: Push Image
        run: | 
          docker push ${{ secrets.DEV_REGISTRY_LOGIN_SERVER }}/backend-dev --all-tags
