name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ 'main' ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.DEV_REGISTRY_LOGIN_SERVER }} 
          username: ${{ secrets.DEV_REGISTRY_USERNAME }}
          password: ${{ secrets.DEV_REGISTRY_PASSWORD }}

      - name: Build Image
        run: |
          docker build -f Dockerfile . -t ${{ secrets.DEV_REGISTRY_LOGIN_SERVER }}/test:${{ github.sha }} \
                                       -t ${{ secrets.DEV_REGISTRY_LOGIN_SERVER }}/test:latest 
      - name: Push Image
        run: | 
          docker push ${{ secrets.DEV_REGISTRY_LOGIN_SERVER }}/test --all-tags

