name: BookXchange Tests 

on:
  workflow_call:
  workflow_dispatch:

jobs:
  django-test:
    runs-on: ubuntu-latest
    env:
      TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
      TEST_DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
      TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      TEST_DB_HOST: ${{ secrets.TEST_DB_HOST }}
    services:
      postgres:
        image: postgres:latest
        env:
          TEST_POSTGRES_USER: ${{ secrets.TEST_DB_USERNAME }}
          TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          TEST_POSTGRES_DB: ${{ secrets.TEST_DB_NAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Setting up Python ${{matrix.python-version}} environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test -v 2